apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: endpoint-reader-binding
  namespace: wso2
subjects:
  - kind: ServiceAccount
    name: wso2svc-account
    apiGroup: ""
roleRef:
  kind: Role
  name: endpoint-reader
  apiGroup: rbac.authorization.k8s.io
